"""textdata may be NULL

Revision ID: 9f7c2e04a7bf
Revises: ed3174b8c2bd
Create Date: 2024-03-24 20:30:00.903787

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9f7c2e04a7bf'
down_revision: Union[str, None] = 'ed3174b8c2bd'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'textdata',
               existing_type=sa.TEXT(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'textdata',
               existing_type=sa.TEXT(),
               nullable=False)
    # ### end Alembic commands ###
